*Date last modified: 1/12/2017
*Purpose: Edit the variable labels 




********************************************************

global ddtah="L:\Data\Data Clean\Wave9\dtah"
global ddo="L:\Data\Data Clean\Wave9"
global dlog="L:\Data\Data Clean\Wave9\log"


*capture clear
capture log close
set more off

log using "${dlog}\label_variable.log", replace

********************************************************

*use "${ddtah}\temp_all.dta", clear

********************************************************

*************************
*    Variable Labels    
*************************

destring wlocrnapb, replace
replace wlocrnapb=wlocnapb if wlocrnapb==. & wlocnapb!=.
drop wlocrnapb

*clear all current labels

foreach x of var _all {

label var `x' 		""

}

*reorder the variable list for labeling

order *_text *_multi*, last


*administrative variables

label var id			"MABEL user ID"
label var listeeid		"AMPCo user ID"
label var sdtype 		"Survey doctor type"
label var source		"Data source"
label var response		"Survey response"
label var continue		"New/Continuing doctor"
label var asgc 			"ASGC remoteness of AMPCo contact address"
label var rrma 			"RRMA remoteness of AMPCo contact address"
label var state 		"State information of AMPCo contact address"
label var type 			"Doctor types provided by AMPCo"
label var cheque 		"Dummy if cheque received with survey"
label var cohort 		"Survey cohort"
label var date 			"Date of survey response"
label var t2response 	"Time to response (days)"

*section A

label var csclid		"Are you currently doing clinical work within Australia?"
label var cspret		"Are you permanently retired from all types of paid work?"
label var csncli		"Doing medical work in Australia that is non-clinical"
label var csml			"Maternity leave"
label var cshd			"Home duties/childcare"
label var csstu			"Enrolled as a student"
label var csexl			"Extended leave"
label var csocli		"Working outside Australia in a clinical role"
label var csoncli		"Working outside Australia in a non-clinical, but medical role"
label var csonmd		"Working outside Australia in a non-medical role"
label var csnmd			"Doing non-medical work in Australia"
label var csnmd_text	"Please state job title"
label var csovs 		"Moved to overseas"
label var csdeath 		"Deceased"
label var csrtn			"Do you intend to return to clinical medical work in Australia"

*section B

label var jsfm			"Freedom to choose your own method of working"
label var jsva			"Amount of variety in your work"
label var jspw			"Physical working conditions"
label var jsau			"Opportunities to use your abilities"
label var jscw			"Your colleagues and fellow workers"
label var jsrc			"Recognition you get for good work"
label var jshw			"Your hours of work"
label var jswr			"Your remuneration"
label var jsrp			"Amount of responsibility you are given"
label var jsfl			"Taking everything into consideration, how do you feel about your work?"
label var jshp			"The amount of work I delegate to other health professionals has increased in the past 12 months"
label var jsbc			"The balance between my personal and professional commitments is about right"
label var jssn			"I have a poor support network of other doctors like me"
label var jsto			"It is difficult to take time off when I want to"
label var jspe			"My patients have unrealistic expectations about how I can help them"
label var jscp			"The majority of my patients have complex health and social problems"
label var jsqs			"I have good support and supervision from qualified specialists"
label var jsps			"Running my practice is stressful most of the time"
label var jsst			"There is enough time for me to do personal study"
label var jspu			"Research publications are important to my career"
label var jspt			"Research publications are important to my training"
label var jsuh			"The hours I work are unpredictable"
label var jssm			"I have good supervision/mentoring support"
label var jslq 			"I often undertake tasks that somebody less qualified could do"
label var jsco 			"I normally consult with others in the practice about the management of patients with complex health and social problems"
label var jsfs 			"Formal structures are in place to encourage communication amongst practice staff"
label var jshe			"I can take time off at short notice, for example if one of my children is ill or for a home emergency"
label var jswl			"My colleagues understand the need for a work-life balance"
label var jslj			"I cannot work my preferred hours due to a lack of jobs offering those hours"
label var jsch			"Would you like to change your hours of work (including day time and after hours)?"
label var jsred			"Imagine you would like to reduce your hours of work. How acheivable is this?"  // GP SP and HD
label var jsredt		"Imagine you would like to reduce your hours of work. How acheivable is this?"   // DE only
label var jsas			"Do you plan to apply for a place on a specialist training course in the future?"
label var jsbsyr		"What year do you expect to begin specialist training? Year"
label var jsbsdk		"Don't know" 
*label var jsbsna 		"Not Applicable" - not in wave 6
label var jssc			"Which specialist training course have you been accepted into/are you waiting to commence?"
label var jssc6			"Specialist course been accepted into - wave 6 onwards"		
label var jsmapna 		"Specialty most like to enrol in: not applicable"
label var jsmaddi 		"Specialty most like to enrol in: Addiction medicine"
label var jsmapan 		"Specialty most like to enrol in: Anaesthesia"
label var jsmapde 		"Specialty most like to enrol in: Dermatology"
label var jsmapem 		"Specialty most like to enrol in: Emergency medicine"
label var jsmapgp 		"Specialty most like to enrol in: General practice"		
label var jsmapic 		"Specialty most like to enrol in: Intensive care medicine"
label var jsmapma 		"Specialty most like to enrol in: Medical administration"
label var jsmapog 		"Specialty most like to enrol in: Obstetrics and gynaecology"
label var jsmapom 		"Specialty most like to enrol in: Occupational and environmental"
label var jsmapop 		"Specialty most like to enrol in: Ophthalmology"
label var jsmappc 		"Specialty most like to enrol in: Paediatrics and child health"
label var jsmapai 		"Specialty most like to enrol in: Pain medicine"
label var jsmappm 		"Specialty most like to enrol in: Palliative"
label var jsmappa 		"Specialty most like to enrol in: Pathology"
label var jsmaphy 		"Specialty most like to enrol in: Physician"
label var jsmapps 		"Specialty most like to enrol in: Psychiatry"
label var jsmapph 		"Specialty most like to enrol in: Public health medicine"
label var jsmapon 		"Specialty most like to enrol in: Radiation oncology"
label var jsmapra 		"Specialty most like to enrol in: Radiology"
label var jsmaprm 		"Specialty most like to enrol in: Rehabilitation medicine"
label var jsmashm 		"Specialty most like to enrol in: Sexual health medicine"
label var jsmaspo 		"Specialty most like to enrol in: Sports and exercise medicine"
label var jsmapsu		"Specialty most like to enrol in: Surgery"
*label var jsmena		"Not Applicable"
label var jsmsome		"Specialty most like to enrol in: Selected at least one option"
label var jsmaoth		"Specialty most like to enrol in: Other specialty"
label var jsmaoth_text	"Specialty most like to enrol in: Other specialty - text"

*section C

label var pwpuhh		"Public hospital (including psychiatric hospital)"
label var pwpihh		"Private hospital"
label var pwpish		"Private medical practitioner's rooms or surgery"
label var pwchh			"Community health centre or other state-run promary care orgnisation"
label var pwhfh			"Residential/aged care health facility (nursing/residential home, hospital etc)"
label var pwahs			"Aboriginal health service"
label var pwlab			"Laboratory or radiology facility"
label var pwgov			"Government department, agency or defence forces"
label var pweih			"Tertiary education institution"
label var pwothh		"Other"
label var pwtoh			"TOTAL HOURS WORKED"
label var pwpip			"Do you work in a private practice?"
label var pwnwmf		"No. of males - Full time"
label var pwnwmp		"No. of males - Part time"
label var pwnwff		"No. of females - Full time"
label var pwnwfp		"No. of females - Part time"
label var pwnwn			"No. of nurses"
label var pwnwap		"No. of allied health professionals"
label var pwnwad		"No. of administrative staff"
label var pwnwo			"No. of other staff"
label var pwcl			"Is your current main practice co-located with other health or welfare professionals?"
label var pwbr			"What is your business relationship with the practice?"
label var pwbr_text		"Please specify the business relationship"
label var pwsmth		"When did you start working at this practice? Month"
label var pwsyr			"When did you start working at this practice? Year"
label var pwoce			"My opportunities for continuing medical education and professional development are:"
label var pwacc 		"Is your practice accredited?"
label var pwni 			"Does your practice claim the Practice Nurse Incentive Program payments?"
label var pwwh			"Do you currently work in a hospital?"
label var pwhlh			"How many hours a week do you work as a hospital locum?"
label var pwmhn			"What is the main hospital in which you work? Hospital name"
label var pwmhp			"What is the main hospital in which you work? Postcode"
label var pwwmth		"How long have you worked at this hospital? Months"
label var pwwyr			"How long have you worked at this hospital? Years"
label var pwahnc		"Have your working arrangement in this hospital changed since the last time you did the MABEL survey?"
label var pwsp			"What is your salaried position?"
label var pwpm			"How are you paid for this hospital?"

*section D

label var wlwh			"Total hours worked per week"
label var wldph			"Direct patient care"
label var wlidph		"Indirect patient care"
label var wleh			"Education activities"
label var wlmh			"Management and administration"
label var wlothh		"Other"
label var wltms			"Teaching medical students"
label var wlttr			"Teaching interns or other pre-vocational trainees"
label var wltrg			"Teaching registrars"
label var wltnt			"No, I am not involved in any teaching"

label var wlacto		"Elected office bearer or board member"
label var wlactc		"Committee member"
label var wlactn		"Not currently involved in any of the above activities"

label var wlana 		"Do you practise in following area: Anaesthetics"
label var wlobs 		"Do you practise in following area: Obstetrics"
label var wlsur 		"Do you practise in following area: Surgery"
label var wleme 		"Do you practise in following area: Emergency medicine"
label var wlnon 		"Do you practise in following area: None of the above"

label var wlspint		"Do you have a special interest in a specific area of clinical practice?"
label var wlante		"Special interest: Antenatal/postnatal care"
label var wlwom			"Special interest: Women's health"
label var wlpsych		"Special interest: Psychological medicine/ mental health"
label var wlskin		"Special interest: Skin cancer/ Dermatology"
label var wlchild		"Special interest: Child/ young person's health"
label var wlsport		"Special interest: Sports medicine"
label var wlotspe		"Special interest: Other"
label var wlot_text		"Special interest: Other (please specify)"
label var wlprop		"Proportion of clinical practice hours accounted for by main area of special interest practice"

label var wlnppc		"Total number of patients seen in private consulting rooms"
label var wlnpph 		"Total number of public patients seen in a public hospital"
label var wlnprh 		"Total number of private patients seen in a public hospital"
label var wlnprr 		"Total number of private patients seen in a private hospital"
label var wlnph			"Total number of patients seen in hospital or other settings"
label var wlnp			"Total number of patients that received care"

label var wlwy			"You, their preferred doctor in the practice?"
label var wlwod			"Any doctor in the pratice?"
label var wlwd			"How long does a NEW patient have to wait for an appointment? Days"
label var wlww			"How long does a NEW patient have to wait for an appointment? Weeks"
label var wlnt			"Not taking patients at present"
label var wlna			"Not Applicable"
label var wlcmin		"How long does a standard private consultation last? MINUTES"
label var wlcnpmin		"How long does a New patient/Initial consultation last? MINUTES"
label var wlcsmin		"How long does a Subsequent consultation last? MINUTES"
label var wlcna			"Not Applicable"
label var wlcf			"What is your current fee for a standard Level B consultation?"
label var wlcnpf		"What is your current fee for a New patient/Initial consultation"
label var wlcnpn		"Most-used item number for initial consultation"
label var wlcsf			"What is your current fee for a Subsequent consultations"
label var wlcsn			"Most-used item number for subsequent consultations"
label var wlcfna		"Not Applicable"
label var wlbbp			"Approximately what percentage of patients do you bulk bill/charge no co-payment?"
label var wlbpna		"Not Applicable"
label var wlah			"Do you do any on-call yourself?"
label var wlocrpn		"1 weeknight in ___ (Practice work)"
label var wlocrhn		"1 weeknight in ___ (Hospital work)"
label var wlocrpe		"1 weekend in ___ (Practice work)"
label var wlocrhe		"1 weekend in ___ (Hospital work)"
label var wlocrnap		"Not Applicable (Practice work)"
label var wlocrnah		"Not Applicable (Hospital work)"
label var wlcotpn		"Weeknights: ___ times per week (Practice work)"
label var wlcothn		"Weeknights: ___ times per week (Hospital work)"
label var wlcotpe		"Weekend: ___ times per weekend (Practice work)"
label var wlcothe		"Weekend: ___ times per weekend (Hospital work)"
label var wlcotnap		"Not Applicable (Practice work)"
label var wlcotnah		"Not Applicable (Hospital work)"
label var wlocrpbn		"1 weeknight in ___ (Public sector work)"
label var wlocrpvn		"1 weeknight in ___ (Private sector work)"
label var wlocrpbe		"1 weekend in ___ (Public sector work)"
label var wlocrpve		"1 weekend in ___ (Private sector work)"
label var wlocnapb		"Not Applicable (Public sector work)"
label var wlocnapv		"Not Applicable (Private sector work)"
*label var wlocrnapv		"Not Applicable (Private sector work)"
label var wlcotpbn		"Weeknights: ___ times per week (Public sector work)"
label var wlcotpvn		"Weeknights: ___ times per week (Private sector work)"
label var wlcotpbe		"Weekend: ___ times per weekend (Public sector work)"
label var wlcotpve		"Weekend: ___ times per weekend (Private sector work)"
label var wlcotnapb		"Not Applicable (Public sector work)"
label var wlcotnapv		"Not Applicable (Private sector work)"
label var wlrh			"How many HOURS were you rostered or listed for on-call?"
label var wlpch			"How many of these HOURS were actually spent in direct patient care?"
label var wlcot			"How many TIMES were you actually called out?"
label var wlocr			"On-call ratio: 1 in ___"
label var wlocna		"Not Applicable"
label var wlocoth		"If your on-call arrangements do not fit the above descriptions, please elaborate below "
label var wlocot		"On-call arrangments do not fit above descriptions. (Imputed variable)"
label var wlal			"Arranging a locum at short notice is usually"
label var wlwhpy		"How many WEEKS holiday did you take in the past year?"
label var wlmlpy		"How many WEEKS of parental or maternity leave did you take in the past year?"
label var wlsdpy		"Approx how many DAYS off work due to illness did you have in the past year?"
label var wlotpy		"Approx how many DAYS off work did you have for other reasons in the past year?"
label var wlhth			"In general, would you say your health is:"
label var wlva 			"No. of vacancies your practice currently has"
label var wlvau 		"No. of vacancies unfilled for 3 months or more"
label var wlvadk 		"No. of vacancies: Don't know"
label var wlvana 		"No. of vacancies: N/A"

*section E

label var figey			"Gross earnings in $ (Before Tax) - ANNUAL"
label var figef			"Gross earnings in $ (Before Tax) - FORTNIGHTLY"
label var finey			"Net earnings in $ (After Tax) - ANNUAL"
label var finef			"Net earnings in $ (After Tax) - FORTNIGHTLY"
*label var finey_neg		"Negative net earnings in $ (After Tax) - ANNUAL"
label var fib			"Did you receive any ongoing 'in kind' benefits or subsidies as part of your current job/s?"
label var fibv			"What is the approximate annual value in dollars of these benefits?"
label var fidme			"What is the total level of financial debt that you currently have as a result of your medical education and training?"
label var fimedk		"Financial debt from education: DK"
label var fidp			"What is the total level of financial debt that you currently have from owning your practice or premises?"
label var fidpdk		"Financial debt from owning practice: DK"
label var fidpna		"Financial debt from owning practice: NA"
label var fips			"What is the status of your private practice for tax purpose?"
*label var fioti		"Do you have other sources of personal income apart from your medical work?" - not in w6
label var fiip			"How much (in dollars) did you pay for professional medical liability, or malpractice, insurance premiums in the last year?"
label var fispm		"% of earnings from services covered by Medicare"
label var fisnpm		"% of earnings from patients for services not covered by Medicare"
label var fisgi		"% of earnings from government incentive schemes and grants"
label var fishw		"% of earnings from hospital work"
label var fisoth		"% of earnings from other sources of medical income"
label var fisadd		"Personal annual gross income received from sources other than medical work"
label var fisadd_neg	"Negative personal annual gross income received from sources other than medical work"
label var fics			"Do you (or your employer) regularly contribute to a superannuation scheme?"
label var ficsyr		"How many years have you contributed to a superannuation scheme?"
label var fiefr			"Given my current financial situation and prospects, I believe I will have enough to live on when I retire."
label var fighiy		"Gross household income (Before Tax) - ANNUAL"
label var fighif		"Gross household income (Before Tax) - FORTNIGHTLY"
label var finhiy		"Net household income (After Tax) - ANNUAL"
label var finhif		"Net household income (After Tax) - FORTNIGHTLY"
*label var finhiy_neg	"Negative net household income (After Tax) - ANNUAL"

*section F

label var glnl			"In how many locations do you practice?"
label var gltww			"Where is your main place of work? Town/Suburb"
label var glpcw			"Where is your main place of work? Postcode"
*label var glmth			"No. of months"
*label var glyr			"No. of years"
label var gltwl			"Where do you live? Town/Suburb"
label var glpcl			"Where do you live? Postcode"
label var glfiw			"I don't have many friends or family members in my current work location"
label var glbl			"It is easy to pursure my hobbies and leisure interests in my current work location"
label var glpfiw		"My partner does not have many friends or family members in this work location"
label var glgeo			"There are good employment opportunities for my partner in this work location"
label var glacsc		"The choice of schools for our children is adequate in this work location"
label var glyrrs		"For how many years did you live in a rural area up until school leaving age?"
label var glrtw			"The main rural area where you lived up until school leaving age: Town"
label var glrst			"The main rural area where you lived up until school leaving age: State"
label var glrna			"Not Applicable"
label var glrl			"Are you subject to restrictions on your location of practise?"
label var glrlpv		"I hold a Permanent Resident Visa"
label var glrltv		"I hold a Temporary Resident Visa"
label var glrlrs		"I am undertaking a return of service period for a Medical Rural Bonded Scholarship or Bonded Medical Place"
label var glrlrp		"I am undertaking a compulsory rural placement as part of my training"
label var glrlot		"Other"
label var glrlna		"Not Applicable"
label var gltps			"Do you travel to provide services/clinics in other geographic areas?"
label var gltown1		"Where are you providing these services? 1st location"
label var glpc1			"Where are you providing these services? 1st postcode"
label var gltown2		"Where are you providing these services? 2nd location"
label var glpc2			"Where are you providing these services? 2nd postcode"
label var gltown3		"Where are you providing these services? 3rd location"
label var glpc3			"Where are you providing these services? 3rd postcode"
label var glnfive		"Are you considering providing services in a non-metro loc in next 5 years?"
label var glnpast		"Have you previously travelled to provide serves in a non-metro loc?"
label var glnfund		"Have you previously received Commonwealth funding to provide services in non-metro"
label var glout1asgc	"ASGC classification of 1st outreach location"
label var glout1rrma	"RRMA classification of 1st outreach location"
label var glout1mmm		"MMM classification of 1st outreach location"
label var glout2asgc	"ASGC classification of 2nd outreach location"
label var glout2rrma	"RRMA classification of 2nd outreach location"
label var glout2mmm		"MMM classification of 2nd outreach location"
label var glout3asgc	"ASGC classification of 3rd outreach location"
label var glout3rrma	"RRMA classification of 3rd outreach location"
label var glout3mmm		"MMM classification of 3rd outreach location"


*section G

label var fclp			"Are you currently living with a partner or spouse?"
label var fcpes			"What is the employment status of your partner/spouse?"
label var fcpmd			"Is your partner/spouse also a medical doctor?"
label var fcpr			"For how many years did your spouse/partner live in a rural area up until the age he/she left secondary school?"
label var fcpr_dk		"Don't know"
label var fcpr_na		"Not applicable"
label var fcprt			"The main rural area where your spouse/partner lived up until school leaving age: Town"
label var fcprs			"The main rural area where your spouse/partner lived up until school leaving age: State"
label var fcprt_dk		"Don't know"
label var fcprt_na		"Not applicable"
label var fcndc			"How many dependent children do you have?"
label var fcayna		"Not Applicable"
label var fcc_age_1		"Age of child 1"
label var fcc_age_2		"Age of child 2"
label var fcc_age_3		"Age of child 3"
label var fcc_age_4		"Age of child 4"
label var fcc_age_5		"Age of child 5"
label var fcc_age_6		"Age of child 6"
label var fcccrf		"Forms of childcare: Relatives or friends"
label var fcccn			"Forms of childcare: Nannies"
label var fccccw		"Forms of childcare: Childcare at work"
label var fcccdc		"Forms of childcare: Other day care"
label var fcccna		"Forms of childcare: Not Applicable"
label var fcrwncc		"I am restricted in my employment and/or the time and hours I work due to a lack of available childcare"
label var fcpwncc		"My partner is restricted in his/her employment and/or the time and hours he/she works due to a lack of available childcare"
label var fcoq			"My partner is overqualified for his/her current job due to the limited availability of suitable jobs"

*section H

label var piyrbi		"Year of birth - imputed"
label var pigeni		"Gender - imputed"
label var piagei 		"Age - imputed"
label var picmd			"In what year did you complete your basic medical degree?"
label var picmda		"Basic medical degree from a medical school in Australia"
label var picmdo		"Basic medical degree from a medical school in the country specified"
label var picmdo_country	"Specified country/region"
label var pims 			"In which medical school in Australia did you complete your basic medical degree?"
label var piis 			"If you completed your medical degree in Australia, were you an international student?"
label var picamc		"If you did your degree at a medical school outside Australia, have you completed the AMC Certificate examination?"
label var pifayr 		"What year did you first arrive in Australia?"
label var pifryr 		"What year were you first registered to work as a doctor in Australia?"
label var pifyrna 		"Not Applicable"
label var piqonr		"Do you have medical qualifications from overseas which are NOT recognised in Australia?"
label var fracgp 		"Does Dr have postgraduate qualification FRACGP?"
label var facrrm 		"Does Dr have postgraduate qualification FACRRM?"
label var fwshpoth 		"Does Dr have postgraduate qualificatiom other than FRACGP and FACRRM?"
label var pimspx		"(wave 1-5) The main specialty in which you practise"
label var pisespx		"(wave 1-5) The second specialty in which you practise"
label var pimsp6		"(wave 6) The main specialty in which you practise"
label var pisesp6		"(wave 6) The second specialty in which you practise"
label var piste			"Spec training program enrolled in?"
label var piste6		"(wave 6) Spec training program enrolled in?"
label var pirsyr		"In what year did you start this training program?"
label var pireyr		"In what year do you expect to complete the program and become a fellow?"
label var pirps 		"Are you training in your preferred specialty? (GP Registrar)"
label var pirna			"Not applicable"
label var pindyr		"How many years and/or months have you spent NOT practising as a doctor since you graduated? Years"
label var pindmt		"How many years and/or months have you spent NOT practising as a doctor since you graduated? Months"
label var pirs			"What is your residency status?"
label var pimrgen	    "Has General Registration"
label var pimrspe       "Has Specialist Registration" 
label var pimrpro       "Has Provisional Registration"
label var pimrlim       "Has Limited Registration"  
label var pimrnon		"Has Non-practising Registration"
label var pilfsa		"All things considered, how satisfied are you with you life in general?"
label var pertj			"Does a thorough job"
label var perct			"Is communicative, talkative"
label var perrd			"Is sometimes somewhat rude to others"
label var peror			"Is original, comes up with new ideas"
label var perwo			"Worries a lot"
label var perfr			"Has a forgiving nature"
label var perlz			"Tends to be lazy"
label var persoc		"Is outgoing, sociable"
label var perart		"Values artistic experiences"
label var pernev		"Gets nervous easily"
label var pereff		"Does things effectively and efficiently"
label var perrsv		"Is reserved"
label var perknd		"Is considerate and kind to others"
label var perimg		"has an active imagination"
label var perstr		"Is relaxed, handles stress well"
label var pilc_1		"I have little control over the things that happen to me"
label var pilc_2		"There is really no way I can solve some of the problems I have"
label var pilc_3		"There is little I can do to change many of the important things in my life"
label var pilc_4		"I often feel helpless in dealing with the problems of life"
label var pilc_5		"Sometimes I feel that I'm being pushed around in life"
label var pilc_6		"What happens to me in the future mostly depends on me"
label var pilc_7		"I can do just about anything I really set my mind on doing"
label var pifirisk		"Likelihood of engaging in financial risks" 
label var picarisk		"Likelihood of engaging in career risks"
label var piclrisk		"Likelihood of engaging in clinical risks"
label var piemail 		"Email address"
label var furcom		"Further comments"

label var pwmhpasgc 	"ASGC classification of main hospital"
label var pwmhprrma 	"RRMA classification of main hospital"
label var pwmhmmm 		"MMM classification of main hospital"
label var gltwwasgc 	"ASGC classification of main place of work"
label var gltwwrrma 	"RRMA classification of main place of work"
label var gltwwmmm	 	"MMM classification of main place of work"
*label var gltwwML 		"Medicare Local Name of main place of work"
label var gltwlasgc 	"ASGC classification of place where respondent lives"
label var gltwlrrma 	"RRMA classification of place where respondent lives"
label var gltwlmmm	 	"MMM classification of place where respondent lives"
label var glrtwasgc 	"ASGC classification of main rural area"
label var glrtwrrma 	"RRMA classification of main rural area"
label var glrtwmmm	 	"MMM classification of main rural area"
label var fcprtasgc 	"ASGC classification of spouse's main rural area"
label var fcprtrrma 	"RRMA classification of spouse's main rural area"
label var fcprtmmm	 	"MMM classification of spouse's main rural area"

label var piin 			"Serious personal injury or illness to self"
label var piinf 		"Serious personal injury or illness to a close relative or family member"
label var pides 		"Death of spouse or child"
label var pider 		"Death of other close relative or family member"
label var pidef 		"Death of a close friend"
label var piviv 		"Victim of physical violence"
label var pivpc 		"Victim of a property crime"
label var pidmn 		"Named as defendant in a medical negligence claim"
label var piinhl 		"How long ago did it happen?"
label var piinfhl 		"How long ago did it happen?"
label var pideshl 		"How long ago did it happen?"
label var piderhl 		"How long ago did it happen?"
label var pidefhl 		"How long ago did it happen?"
label var pivivhl 		"How long ago did it happen?"
label var pivpchl 		"How long ago did it happen?"
label var pidmnhl 		"How long ago did it happen?"

label var pisapna 		"Spec course applied for in past: None, not applicable"
label var pisappc 		"Spec course applied for in past: Paediatrics and Child Health"
label var pisappm 		"Spec course applied for in past: Palliative Medicine"
label var pisaprm 		"Spec course applied for in past: Rehabilitation Medicine"
label var pisapde 		"Spec course applied for in past: Dermatology"
label var pisapma 		"Spec course applied for in past: Medical Administration"
label var pisapop 		"Spec course applied for in past: Ophthalmology"
label var pisapps 		"Spec course applied for in past: Psychiatry"
label var pisapsu 		"Spec course applied for in past: Surgery"
label var pisapgp		"Spec course applied for in past: GP"
label var pisapom 		"Spec course applied for in past: Occupational Medicine"
label var pisapph 		"Spec course applied for in past: Public Health Medicine"
label var pisapan 		"Spec course applied for in past: Anaesthesia"
label var pisapem 		"Spec course applied for in past: Emergency Medicine"
label var pisapic 		"Spec course applied for in past: Intensive Care Medicine"
label var pisapog 		"Spec course applied for in past: Obstetrics and Gynaecology"
label var pisappa 		"Spec course applied for in past: Pathology"
label var pisapra 		"Spec course applied for in past: Radiology"
label var pisaddi 		"Spec course applied for in past: Addiction"
label var pisapai 		"Spec course applied for in past: Pain Medicine"
label var pisapim 		"Spec course applied for in past: Physician"
label var pisapon 		"Spec course applied for in past: Radiation Oncology"
label var pisashm 		"Spec course applied for in past: Sexual Health Medicine"
label var pisaspo 		"Spec course applied for in past: Sport and Exercise Medicine"

*label var piqanu 		"Number of Undergraduate degree"
*label var piqang 		"Number of Gradute entry medical degree"
label var piqanm 		"Number of Masters degree"
label var piqanph 		"Number of PhD degree"
label var piqandc 		"Number of Postgraduate diploma/certificate"
label var piqanf 		"Number of Fellowship qualification of college"
*label var piqanot 		"Number of other qualifications"

*label var piqadu 		"Undergraduate medical degree"
*label var piqadg 		"Gradute entry medical degree"
label var piqadf 		"Fellowship qualifications"

label var pires			"Research degree from medical school"
label var pioth			"Other quals obtained in Australia (in last 12 months if cont Dr)"





*check all values have labels where neccessary
foreach v of varlist _all {
 local vl: variable label `v'	
		if "`vl'"=="" {
			di
			di "==========[ `f' : `v': varlabel missing ]=========="
		}
	}	



